"use client";
import { useEffect, useMemo, useState } from "react";

function Probability({ label, value, tone }) { return <div className="probability"><div className="probability-label"><span>{label}</span><strong>{value}%</strong></div><div className="track"><span className={tone} style={{ width: `${value}%` }} /></div></div>; }
function MatchCard({ match }) {
  const pick = Math.max(match.prediction.home, match.prediction.draw, match.prediction.away);
  const pickLabel = pick === match.prediction.home ? match.home : pick === match.prediction.away ? match.away : "Barazim";
  return <article className="match-card"><div className="match-meta"><span>{match.league}</span><span className={match.status === "LIVE" ? "live" : "scheduled"}>{match.status === "LIVE" ? `● LIVE ${match.minute}'` : "SË SHPEJTI"}</span></div><div className="scoreboard"><div className="team"><div className="crest">{match.homeLogo ? <img src={match.homeLogo} alt="" /> : match.home.slice(0, 2).toUpperCase()}</div><strong>{match.home}</strong></div><div className="score"><span>{match.homeGoals}</span><small>—</small><span>{match.awayGoals}</span></div><div className="team"><div className="crest">{match.awayLogo ? <img src={match.awayLogo} alt="" /> : match.away.slice(0, 2).toUpperCase()}</div><strong>{match.away}</strong></div></div><div className="insight"><span>PARASHIKIMI AI</span><strong>{pickLabel}</strong><em>{match.prediction.confidence}% besueshmëri</em></div><div className="probabilities"><Probability label="Vendas" value={match.prediction.home} tone="green" /><Probability label="Barazim" value={match.prediction.draw} tone="gold" /><Probability label="Mysafir" value={match.prediction.away} tone="blue" /></div></article>;
}

export default function Home() {
  const [data, setData] = useState({ matches: [], source: "loading" }), [error, setError] = useState(""), [filter, setFilter] = useState("Të gjitha");
  async function load() { try { const response = await fetch("/api/matches", { cache: "no-store" }); if (!response.ok) throw new Error("Nuk u morën ndeshjet"); setData(await response.json()); setError(""); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  const leagues = useMemo(() => ["Të gjitha", ...new Set(data.matches.map((m) => m.league))], [data.matches]);
  const matches = filter === "Të gjitha" ? data.matches : data.matches.filter((m) => m.league === filter);
  return <main><nav><a className="brand" href="#"><span>FA</span> Football AI <b>PRO</b></a><div className="nav-status"><i /> AI Engine aktiv</div></nav><section className="hero"><div><p className="eyebrow">INTELIGJENCË NË KOHË REALE</p><h1>Lexoje lojën.<br /><span>Para se të mbarojë.</span></h1><p className="intro">Analizë live, probabilitete dinamike dhe parashikime të qarta për ndeshjet që po zhvillohen tani.</p></div><div className="hero-stat"><strong>{data.matches.filter((m) => m.status === "LIVE").length}</strong><span>ndeshje live</span><small>Përditësim çdo 30 sekonda</small></div></section><section className="toolbar"><div><h2>Ndeshjet</h2><p>{data.source === "live" ? "Të dhëna live" : data.source === "loading" ? "Duke u ngarkuar…" : "Modalitet demonstrues"}</p></div><button onClick={load}>↻ Përditëso</button></section><div className="filters">{leagues.map((league) => <button className={filter === league ? "active" : ""} key={league} onClick={() => setFilter(league)}>{league}</button>)}</div>{error && <p className="error">{error}</p>}<section className="grid">{matches.map((match) => <MatchCard key={match.id} match={match} />)}</section><footer><span>Football AI Live Pro</span><p>Parashikimet janë informative dhe nuk garantojnë rezultate.</p></footer></main>;
}
